==== COURSE ==== 

Process Oriented Programming (1DT049) Spring 2012

Department of Information Technology 
Uppsala university


==== GROUP ==== 

02 (change this to your group number).


==== PROJECT NAME ==== 

Awesome Evolution Simulator


==== PROJECT DESCRIPTION ==== 

We are building an evolution simulator. You will be able to start a world
with some parameters, and from there single step and see how things develop.


==== GROUP MEMBERS ==== 


890112-0413 Erik.Samuelsson.6051@student.uu.se
880728-0493 Emilcarlmartin.Vikstrom.8189@student.uu.se
            Alexander.Persson.9613@student.uu.se
810416-7138 patrik@patrikbroman.se



==== MAY THE SOURCE BE WITH YOU ==== 

Everything you need to compile and run the system is included in this
directory. 

However, you might want to get the most up to date version of this
directory. 

Add a description here on how to use Subversion, Git or similar to get
the most up to date version of this directory. 

==== ERLANG VERSION ====

This software was developed and tested using Erlang R14B03.
     	      	  	    	       
==== MAKE IT HAPPEN ==== 

Using the make utility you can perform the following actions:

make         ==> Compiles the Erlang source files if necessary. 
make archive ==> Creates a gziped tar archive of this directory. 
make clean   ==> Removes all beam files and html files generated by Edoc.
make doc     ==> Generates Edoc documentation in the doc/html directory.
make start   ==> Starts the system.
make test    ==> Runs all Eunit tests.


==== TO COMPILE ==== 

To compile the project, simply type make and press enter.


==== TO RUN AND TEST THE SYSTEM ==== 

Add a short description on how to run and test your system. Here you
might give pointers to more details in the doc/final_presentation.pdf
document. 

If possible, add targets to the Makefile that can be used to start the
system (make start, make start_server, make start_client or similar as
necessary). 

==== MORE INFORMATION (optional) ==== 

 * How to get more information about your project?
 * Who is the main contact person?
 * Do you have a project home page?
